# Generated by Django 2.0.4 on 2018-05-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=120)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.CharField(max_length=120)),
                ('picture', models.ImageField(upload_to='static/media')),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('link', models.URLField(max_length=120)),
                ('owner', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='static/media')),
            ],
        ),
    ]
