# Generated by Django 2.0.4 on 2018-05-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='country',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breed',
            name='is_official',
            field=models.BooleanField(default=True),
        ),
    ]
